/* Kripipasta shared dossier data — UI chrome (per language) + entities (per id, per language).
   Loaded as a plain script; exposes window.KripiData = { UI, ENTITIES, order }. */
(function () {
  const UI = {
    en: {
      subtitle: 'Internet Horror Archive', searchArchive: 'Search the archive', contentsLabel: 'Contents', catLabel: 'Categories',
      cat0: 'Cryptids', cat1: 'Classic Creepypasta', cat2: 'Analog Horror', cat3: 'Urban Legends', cat4: 'Entities',
      recentLabel: 'Recently viewed', estLabel: 'EST. MMV · COMMUNITY-EDITED',
      bcArchive: 'Archive', contribMeta: '34 contributors', lastEdited: 'Last edited 3 days ago · revision 12',
      statFirst: 'First surfaced', statOrigin: 'Origin', statThreat: 'Threat level', statPop: 'Popularity', scrollWord: 'SCROLL',
      maintainedPre: 'Maintained by ', editorsLink: 'the Kripipasta editors', editArticle: 'Edit article', historyBtn: 'History',
      orNoteLabel: 'EDITOR’S NOTE', encRevealT: 'Reveal spoiler', encRevealS: 'A widely-cited detail from the account',
      galHint: 'Click to expand', threatWord: 'THREAT', thRevealT: 'Reveal a darker theory', thRevealS: 'Read at your discretion',
      pendingLabel: 'PENDING', approveBtn: 'Approve · 27', discussBtn: 'Discuss', suggestLink: 'Suggest a lore update →',
      discussionLabel: 'Discussion', topLabel: 'Top', newLabel: 'New', addPlaceholder: 'Add to the discussion…', postBtn: 'Post', replyWord: 'Reply', shareWord: 'Share',
      readingProgress: 'Reading progress', miniRead: 'Read', miniScore: 'Score', miniSaves: 'Saves',
      factsLabel: 'Character Facts', fThreat: 'Threat level', fDanger: 'Danger score', fPop: 'Popularity',
      gSpecies: 'Species', gStatus: 'Status', gCreator: 'Creator', gYear: 'Year', gHeight: 'Height', gCanon: 'Canon', gHabitat: 'Habitat',
      communityScore: 'Community Score', credibleSuffix: 'found this entry credible', reactionsLabel: 'Reactions',
      popularWeek: 'Popular This Week', trendingLabel: 'Trending Entities', randomBtn: 'Open a random entry',
      favOff: 'Favorite', favOn: 'Favorited', bookOff: 'Save', bookOn: 'Saved', copyOff: 'Copy link', copyOn: 'Link copied',
      tocLabels: ['Overview', 'Origin Story', 'Internet History', 'Behavior & Abilities', 'Weaknesses', 'Documented Encounters', 'Gallery', 'Popularity Over Time', 'Fan Theories', 'Myths & Misconceptions', 'Related Entities', 'Community Notes', 'References'],
      reactionLabels: ['Unsettled', 'Chills', 'Fascinated', 'Skeptical'],
      popular: [
        { name: 'Slender Man', meta: 'Classic · 2009' },
        { name: 'The Backrooms', meta: 'Liminal · 2019' },
        { name: 'BEN Drowned', meta: 'Lost media · 2010' },
        { name: 'Siren Head', meta: 'Cryptid · 2018' },
        { name: 'Candle Cove', meta: 'Lost episode · 2009' },
      ],
      trending: [
        { name: 'The Mandela Catalogue', delta: '+41%' },
        { name: 'The Walten Files', delta: '+33%' },
        { name: 'Local58', delta: '+27%' },
        { name: 'The Backrooms', delta: '+19%' },
      ],
    },
    ru: {
      subtitle: 'Архив интернет-хоррора', searchArchive: 'Поиск по архиву', contentsLabel: 'Содержание', catLabel: 'Категории',
      cat0: 'Криптиды', cat1: 'Классические крипипасты', cat2: 'Аналоговый хоррор', cat3: 'Городские легенды', cat4: 'Сущности',
      recentLabel: 'Недавно просмотрено', estLabel: 'ОСН. MMV · РЕДАКТИРУЕТСЯ СООБЩЕСТВОМ',
      bcArchive: 'Архив', contribMeta: '34 участника', lastEdited: 'Последняя правка 3 дня назад · ревизия 12',
      statFirst: 'Впервые замечен', statOrigin: 'Происхождение', statThreat: 'Уровень угрозы', statPop: 'Популярность', scrollWord: 'ВНИЗ',
      maintainedPre: 'Ведётся ', editorsLink: 'редакторами Kripipasta', editArticle: 'Редактировать', historyBtn: 'История',
      orNoteLabel: 'ОТ РЕДАКЦИИ', encRevealT: 'Показать спойлер', encRevealS: 'Часто цитируемая деталь рассказа',
      galHint: 'Нажмите, чтобы открыть', threatWord: 'УГРОЗА', thRevealT: 'Показать теорию потемнее', thRevealS: 'Читайте на свой страх и риск',
      pendingLabel: 'НА РАССМОТРЕНИИ', approveBtn: 'Одобрить · 27', discussBtn: 'Обсудить', suggestLink: 'Предложить правку лора →',
      discussionLabel: 'Обсуждение', topLabel: 'Топ', newLabel: 'Новые', addPlaceholder: 'Добавить к обсуждению…', postBtn: 'Отправить', replyWord: 'Ответить', shareWord: 'Поделиться',
      readingProgress: 'Прогресс чтения', miniRead: 'Чтение', miniScore: 'Оценка', miniSaves: 'Сохран.',
      factsLabel: 'Факты о персонаже', fThreat: 'Уровень угрозы', fDanger: 'Опасность', fPop: 'Популярность',
      gSpecies: 'Вид', gStatus: 'Статус', gCreator: 'Создатель', gYear: 'Год', gHeight: 'Рост', gCanon: 'Канон', gHabitat: 'Среда',
      communityScore: 'Оценка сообщества', credibleSuffix: 'считают запись достоверной', reactionsLabel: 'Реакции',
      popularWeek: 'Популярное за неделю', trendingLabel: 'В тренде', randomBtn: 'Открыть случайную запись',
      favOff: 'В избранное', favOn: 'В избранном', bookOff: 'Сохранить', bookOn: 'Сохранено', copyOff: 'Копировать ссылку', copyOn: 'Ссылка скопирована',
      tocLabels: ['Обзор', 'История происхождения', 'История в интернете', 'Поведение и способности', 'Слабые места', 'Задокументированные встречи', 'Галерея', 'Популярность со временем', 'Фанатские теории', 'Мифы и заблуждения', 'Связанные сущности', 'Заметки сообщества', 'Источники'],
      reactionLabels: ['Тревожно', 'Мурашки', 'Увлекательно', 'Скептично'],
      popular: [
        { name: 'Slender Man', meta: 'Классика · 2009' },
        { name: 'The Backrooms', meta: 'Лиминальное · 2019' },
        { name: 'BEN Drowned', meta: 'Потерянные плёнки · 2010' },
        { name: 'Siren Head', meta: 'Криптид · 2018' },
        { name: 'Candle Cove', meta: 'Потерянная серия · 2009' },
      ],
      trending: [
        { name: 'The Mandela Catalogue', delta: '+41%' },
        { name: 'The Walten Files', delta: '+33%' },
        { name: 'Local58', delta: '+27%' },
        { name: 'The Backrooms', delta: '+19%' },
      ],
    },
  };

  const ENTITIES = {
    'the-rake': {
      threatBar: 82, dangerBar: 74, popBar: 91, starPct: 92, votesUp: 2841, votesDown: 137,
      reactions: { unsettled: 214, chills: 389, fascinated: 512, skeptical: 73 },
      chart: { years: [2005, 2008, 2011, 2014, 2017, 2020, 2023, 2025], vals: [22, 49, 71, 60, 45, 66, 84, 91] },
      heroImg: '', galleryImgs: ['', '', '', '', ''],
      en: {
        name: 'The Rake', altName: 'Hminnu', alsoPre: '“The Pale Watcher” · also archived as ', bcCat: 'Cryptids', kicker1: 'Cryptid Dossier · Entity', kicker2: 'Community Canon',
        heroFirstV: '2005', heroOriginV: 'N. America', heroThreatV: 'Severe', heroPopV: '91', readTime: '18 min read', ratingMeta: '/ 5 · 3,120 ratings',
        lead: 'A gaunt, pale humanoid said to crouch at the foot of a sleeper’s bed and watch — patiently, without sound — until the moment it decides to move.',
        ovP1: 'The Rake has no confirmed origin, no author, and no single canonical text. Instead it exists as the sum of thousands of overlapping accounts — each one insisting it happened to someone the teller almost knew. That collaborative authorship is precisely why it endures.',
        ovP2: 'Where most internet horror is a story you read, the Rake is a story you are told you might already be inside of — a figure defined less by what it does than by the certainty that it is watching before you ever wake.',
        ovQuote: '“It didn’t blink. It waited at the end of the bed until I made myself look — and by then it was already closer.”',
        ovQuoteFoot: 'Recurring line — aggregated eyewitness accounts',
        orP1: 'The modern Rake was assembled in 2005, in a series of image-board threads where anonymous users agreed, in real time, to build a monster together. Someone proposed a creature; others supplied “recovered” evidence — a 12th-century mention, a mistranslated name, a ship’s log, a mother’s video — none of which ever existed outside the thread.',
        orP2: 'This is fiction wearing the costume of provenance. The fabricated documents were designed to feel found rather than written, and that single move — presenting invention as archive — became the template for a decade of internet horror that followed.',
        orNote: 'The 1691 record and the “ship’s log” frequently cited in retellings originate from the 2005 thread itself. They are not historical sources, and the archive flags them as fabricated throughout.',
        history: [
          { t: '2005 · Assembled', b: 'Built across anonymous threads; the collaborative “evidence” is written and mirrored within days.' },
          { t: '2006 · The lake-house account', b: 'A single detailed “sighting” surfaces and is later treated as the definitive canonical text.' },
          { t: '2010–2013 · Mass audience', b: 'YouTube retellings and short films carry the figure far beyond its origin community.' },
          { t: '2018 · Analog-horror wave', b: 'Reframed as “recovered footage,” the Rake fits neatly into a new documentary-horror grammar.' },
          { t: '2024 · Revival', b: 'A relaunch series and renewed academic interest in collaborative folklore drive a fresh peak.' },
        ],
        behavior: [
          { t: 'Watches, then acts', x: 'Long periods of stillness at the foot of the bed precede any movement.' },
          { t: 'Unnatural crawl', x: 'Moves in a low crawl; disproportionately fast over short distances.' },
          { t: 'Peripheral only', x: 'Reported most often at the edge of vision; rarely seen head-on.' },
          { t: 'The half-heard voice', x: 'A whisper witnesses cannot reconstruct afterward is frequently reported.' },
        ],
        wk: 'No physical vulnerability has ever been documented. The single consistent “defense” across accounts is perception itself: the Rake reportedly retreats — or simply is no longer there — the instant it is looked at directly, or a light is turned on. Whether that is a property of the creature or of the half-waking mind describing it is exactly the ambiguity the story depends on.',
        encFrom: 'From the 2006 account',
        encIntro: 'A handful of accounts recur often enough to be treated, within the community, as canonical. The most cited omits a detail many retellings consider the genuinely unsettling part.',
        encBody: 'In the most-repeated version, the witness claims they understood a single sentence it spoke — and that everyone who hears the sentence repeated aloud sleeps worse for weeks. The “sentence” is never written down the same way twice.',
        galleryData: [
          { label: 'concept portrait', cap: 'Community concept portrait — the most-reproduced likeness (artist unknown).' },
          { label: 'recovered frame', cap: 'Frame from the 2006 lake-house account, widely circulated and never verified.' },
          { label: 'field sketch', cap: 'Eyewitness sketch submitted with a 2009 report.' },
          { label: 'sighting map', cap: 'Aggregated sighting locations across North America, 2005–present.' },
          { label: 'analog still', cap: 'Still from the 2019 analog-horror revival series.' },
        ],
        popCap: 'Search and mention volume, indexed to 100. The 2018 analog-horror revival and the 2023 relaunch drove the sharpest gains.',
        theories: [
          { t: 'Sleep-paralysis externalization', x: 'A shared name for a near-universal hypnopompic hallucination — the figure at the foot of the bed that thousands describe independently.' },
          { t: 'Memetic entity', x: 'It “exists” only insofar as it is retold, and each retelling strengthens it. The story is the organism.' },
          { t: 'The self-reinforcing reading', x: 'This theory frames the article you are reading as part of the mechanism — the more you research it before sleeping, the more likely you are to “see” it. Attention is the only thing it actually feeds on.' },
        ],
        myths: [
          { t: 'Not Slender Man', x: 'The two are frequently merged but have separate origins and distinct behaviors.' },
          { t: 'No medieval source', x: 'The “historical” documents are modern fabrications written into the 2005 thread.' },
          { t: 'No single video', x: 'The canonical “footage” is a composite of many uploads, not one authoritative clip.' },
        ],
        references: [
          'Anonymous image-board thread archive, 2005 (community mirror).',
          '“Building a Monster Together,” essay on collaborative creepypasta, 2016.',
          'The 2006 “lake-house” account, community transcription.',
          'Analog-horror revival series, 2018–2020.',
          '“Folklore & the Internet,” journal survey, 2021.',
          'Sighting aggregation dataset, community-maintained, 2005–present.',
        ],
        related: [
          { id: 'slender-man', name: 'Slender Man', rel: 'Frequently conflated', threat: 88 },
          { id: 'the-expressionless', name: 'The Expressionless', rel: 'Shared watcher motif', threat: 71 },
          { id: 'hachishakusama', name: 'Hachishakusama', rel: 'Nocturnal observer archetype', threat: 79 },
          { id: 'the-smiling-man', name: 'The Smiling Man', rel: 'Street-level analog', threat: 64 },
        ],
        noteText: '3 contributors suggest adding a subsection on regional variants — the “crawler” accounts from the Pacific Northwest. Vote to prioritize.',
        comments: [
          { author: 'm_hollow', role: 'Editor', time: '2 days ago', text: 'Added a note on the 1691 ship’s log being a later fabrication — it comes from the 2005 thread, not any real archive.', votes: 64 },
          { author: 'quietfrequency', role: 'Contributor', time: '5 days ago', text: 'The peripheral-vision detail is the scariest part and the most consistent across accounts. Worth its own subsection?', votes: 41 },
          { author: 'north_ny_2006', role: 'Reader', time: '1 week ago', text: 'Grew up near the lake in the original account. The story warped a lot in retelling — good to see it documented carefully.', votes: 28 },
        ],
        facts: { fThreatV: '82 · Severe', fDangerV: '74', fPopV: '91', species: 'Humanoid', status: 'Active', creator: 'Collaborative', year: '2005', height: '~6 ft', canon: 'Community', habitat: 'Rural bedrooms · treelines · lake houses' },
        scoreNum: '4.6', ratingsCount: '3,120 ratings',
      },
      ru: {
        name: 'The Rake', altName: 'Hminnu', alsoPre: '«Бледный наблюдатель» · также в архиве как ', bcCat: 'Криптиды', kicker1: 'Досье криптида · Сущность', kicker2: 'Канон сообщества',
        heroFirstV: '2005', heroOriginV: 'Сев. Америка', heroThreatV: 'Высокая', heroPopV: '91', readTime: '18 мин чтения', ratingMeta: '/ 5 · 3 120 оценок',
        lead: 'Худой бледный гуманоид, что, по слухам, сидит на корточках в изножье кровати спящего и смотрит — терпеливо, беззвучно — пока не решит двинуться.',
        ovP1: 'У Грабель нет ни подтверждённого происхождения, ни автора, ни единого канонического текста. Вместо этого они существуют как сумма тысяч пересекающихся рассказов — каждый уверяет, что это случилось с кем-то, кого рассказчик почти знал. Именно это коллективное авторство и делает их живучими.',
        ovP2: 'Если большинство интернет-хоррора — это история, которую вы читаете, то Грабли — история, о которой вам говорят, что вы, возможно, уже внутри неё.',
        ovQuote: '«Он не моргал. Он ждал в изножье кровати, пока я не заставил себя посмотреть, — и к тому времени он был уже ближе.»',
        ovQuoteFoot: 'Повторяющаяся фраза — сводные показания очевидцев',
        orP1: 'Современные Грабли были собраны в 2005 году в серии тредов на имиджбордах, где анонимы в реальном времени договорились вместе построить монстра.',
        orP2: 'Это вымысел в костюме достоверности. Поддельные документы были созданы так, чтобы казаться найденными, а не написанными.',
        orNote: 'Запись 1691 года и «судовой журнал», часто цитируемые в пересказах, происходят из самого треда 2005 года. Это не исторические источники, и архив повсюду помечает их как сфабрикованные.',
        history: [
          { t: '2005 · Собраны', b: 'Собраны в анонимных тредах; коллективные «доказательства» пишутся и зеркалируются за считанные дни.' },
          { t: '2006 · Рассказ о доме у озера', b: 'Всплывает один подробный «случай», позже принятый за окончательный канонический текст.' },
          { t: '2010–2013 · Массовая аудитория', b: 'Пересказы на YouTube и короткометражки уносят фигуру далеко за пределы породившего её сообщества.' },
          { t: '2018 · Волна аналог-хоррора', b: 'Переосмысленные как «найденная плёнка», Грабли идеально вписываются в новую грамматику документального хоррора.' },
          { t: '2024 · Возрождение', b: 'Сериал-перезапуск и новый академический интерес к коллективному фольклору дают свежий пик.' },
        ],
        behavior: [
          { t: 'Сначала наблюдает', x: 'Долгие периоды неподвижности в изножье кровати предшествуют любому движению.' },
          { t: 'Неестественная походка', x: 'Передвигается низким ползком; на коротких дистанциях непропорционально быстр.' },
          { t: 'Только боковым зрением', x: 'Чаще всего замечают на краю поля зрения; прямо — крайне редко.' },
          { t: 'Полуразличимый голос', x: 'Свидетели часто сообщают о шёпоте, который потом не могут воспроизвести.' },
        ],
        wk: 'Никакой физической уязвимости так и не задокументировано. Единственная устойчивая «защита» — само восприятие: Грабли отступают в тот миг, когда на них смотрят прямо или включают свет.',
        encFrom: 'Из рассказа 2006 года',
        encIntro: 'Несколько рассказов повторяются достаточно часто, чтобы в сообществе их считали каноническими. В самом цитируемом из них опущена деталь, которую многие пересказы считают по-настоящему тревожной.',
        encBody: 'В самой распространённой версии свидетель утверждает, что понял единственную произнесённую им фразу — и что каждый, кто слышит эту фразу вслух, потом неделями спит хуже. «Фразу» ни разу не записали одинаково.',
        galleryData: [
          { label: 'концепт-портрет', cap: 'Концепт-портрет от сообщества — самое тиражируемое изображение (автор неизвестен).' },
          { label: 'восстановленный кадр', cap: 'Кадр из рассказа о доме у озера 2006 года, широко разошёлся и никогда не был подтверждён.' },
          { label: 'полевой набросок', cap: 'Набросок очевидца, приложенный к отчёту 2009 года.' },
          { label: 'карта появлений', cap: 'Сводные места появлений по Северной Америке, 2005 — настоящее время.' },
          { label: 'аналоговый стоп-кадр', cap: 'Стоп-кадр из сериала-возрождения аналогового хоррора 2019 года.' },
        ],
        popCap: 'Объём поисковых запросов и упоминаний, индекс 100. Возрождение аналог-хоррора 2018 года и перезапуск 2023 года дали самый резкий рост.',
        theories: [
          { t: 'Экстернализация сонного паралича', x: 'Общее имя для почти универсальной гипнопомпической галлюцинации — фигуры в изножье кровати, которую тысячи описывают независимо друг от друга.' },
          { t: 'Мемная сущность', x: 'Существует лишь постольку, поскольку её пересказывают, и каждый пересказ её усиливает. Организм — это сама история.' },
          { t: 'Самоподдерживающееся прочтение', x: 'Эта теория представляет статью, которую вы читаете, частью механизма — чем больше вы изучаете его перед сном, тем вероятнее «увидите». Внимание — единственное, чем оно действительно питается.' },
        ],
        myths: [
          { t: 'Не Слендермен', x: 'Их часто смешивают, но у них разное происхождение и разное поведение.' },
          { t: 'Нет средневекового источника', x: '«Исторические» документы — современные подделки, вписанные в тред 2005 года.' },
          { t: 'Нет единого видео', x: 'Каноническая «запись» — компоновка множества загрузок, а не один авторитетный клип.' },
        ],
        references: [
          'Архив анонимного треда с имиджборда, 2005 (зеркало сообщества).',
          '«Строим монстра вместе», эссе о коллективном крипипасте, 2016.',
          'Рассказ о «доме у озера» 2006 года, транскрипция сообщества.',
          'Серия возрождения аналог-хоррора, 2018–2020.',
          '«Фольклор и интернет», журнальный обзор, 2021.',
          'Датасет агрегации наблюдений, поддерживается сообществом, 2005 — настоящее время.',
        ],
        related: [
          { id: 'slender-man', name: 'Slender Man', rel: 'Часто путают', threat: 88 },
          { id: 'the-expressionless', name: 'The Expressionless', rel: 'Общий мотив наблюдателя', threat: 71 },
          { id: 'hachishakusama', name: 'Hachishakusama', rel: 'Архетип ночного наблюдателя', threat: 79 },
          { id: 'the-smiling-man', name: 'The Smiling Man', rel: 'Уличный аналог', threat: 64 },
        ],
        noteText: '3 участника предлагают добавить подраздел о региональных вариантах — рассказы о «ползуне» с северо-запада США. Голосуйте за приоритет.',
        comments: [
          { author: 'm_hollow', role: 'Редактор', time: '2 дня назад', text: 'Добавил заметку о том, что «судовой журнал» 1691 года — поздняя подделка: он из треда 2005 года, а не из настоящего архива.', votes: 64 },
          { author: 'quietfrequency', role: 'Участник', time: '5 дней назад', text: 'Деталь с боковым зрением — самая жуткая и самая устойчивая в рассказах. Достойна отдельного подраздела?', votes: 41 },
          { author: 'north_ny_2006', role: 'Читатель', time: '1 неделю назад', text: 'Вырос у того самого озера из оригинального рассказа. При пересказах история сильно исказилась — приятно видеть аккуратную документацию.', votes: 28 },
        ],
        facts: { fThreatV: '82 · Высокая', fDangerV: '74', fPopV: '91', species: 'Гуманоид', status: 'Активен', creator: 'Коллективный', year: '2005', height: '~1,8 м', canon: 'Сообщество', habitat: 'Сельские спальни · опушки · дома у озёр' },
        scoreNum: '4.6', ratingsCount: '3 120 оценок',
      },
    },

    'slender-man': {
      threatBar: 88, dangerBar: 80, popBar: 96, starPct: 96, votesUp: 9210, votesDown: 330,
      reactions: { unsettled: 402, chills: 690, fascinated: 741, skeptical: 118 },
      chart: { years: [2009, 2011, 2013, 2015, 2017, 2020, 2023, 2025], vals: [30, 88, 74, 52, 47, 63, 79, 96] },
      heroImg: '', galleryImgs: ['', '', '', '', ''],
      en: {
        name: 'Slender Man', altName: 'Der Großmann', alsoPre: '“The Thin Man” · also archived as ', bcCat: 'Classic Creepypasta', kicker1: 'Modern Myth · Entity', kicker2: 'Community Canon',
        heroFirstV: '2009', heroOriginV: 'Web forum', heroThreatV: 'Severe', heroPopV: '96', readTime: '21 min read', ratingMeta: '/ 5 · 9,540 ratings',
        lead: 'A tall, faceless figure in a dark suit that lingers at the treeline — and seems to thin the thoughts of anyone who looks too long, or for too many nights, for it.',
        ovP1: 'Slender Man is the first internet monster with a knowable birthday. Unlike the folklore it imitates, it did not drift out of oral tradition — it was posted, dated, and credited, then adopted so completely that many people now assume it must be older than it is.',
        ovP2: 'What makes it durable is its emptiness. A featureless face is a screen: every reader projects their own dread onto it, and every retelling is free to redecorate the figure without breaking it. The blankness is the design.',
        ovQuote: '“We didn’t want to go, but he was waiting past the fence, and somehow the photographs came back with him already in them.”',
        ovQuoteFoot: 'Composite line — early forum retellings',
        orP1: 'Slender Man was created in June 2009 by Eric Knudsen, posting as “Victor Surge,” for a Something Awful thread challenging users to paste paranormal figures into ordinary photographs. Two doctored black-and-white images — a thin figure behind children — arrived with invented captions about missing kids.',
        orP2: 'Within weeks other users were writing “sightings,” faking documents, and cross-linking each other’s inventions until no single author remained. The photo contest had become a collaborative mythology, and its rules — treat the fake as found — set the pattern for a decade of creepypasta.',
        orNote: 'Slender Man has a documented author and creation date. Any “ancient woodcut” or “German fairy-tale” framing you encounter is a later fan embellishment, not a source, and the archive marks such claims accordingly.',
        history: [
          { t: '2009 · Created', b: 'Posted to a Something Awful photo-editing thread; other users begin building lore around the two original images almost immediately.' },
          { t: '2010 · Marble Hornets', b: 'A found-footage YouTube series recasts the figure as a filmable, stalking presence and defines its visual grammar.' },
          { t: '2012 · Games', b: 'A minimalist survival game spreads the character to a mass audience far beyond the origin forums.' },
          { t: '2014 · Public scrutiny', b: 'A real-world crime committed by minors who invoked the character draws heavy media attention and debate about online folklore.' },
          { t: '2018–2024 · Film & study', b: 'A feature film and growing academic interest in born-digital myth keep the figure in wide circulation.' },
        ],
        behavior: [
          { t: 'Impossible height', x: 'Described as unnaturally tall and thin, often lengthening or contorting when unobserved.' },
          { t: 'The blank face', x: 'A featureless white head; witnesses report unease they struggle to explain afterward.' },
          { t: 'Reaching limbs', x: 'Later accounts add long, tentacle-like appendages used to corral or carry.' },
          { t: 'Fixation & static', x: 'Prolonged attention is said to bring memory gaps, paranoia, and camera distortion.' },
        ],
        wk: 'As with most collaborative entities, no reliable weakness is agreed upon — the figure is defined by inevitability rather than by rules that can be broken. The most common “protection” across accounts is simply refusing to seek it out: attention, filming, and obsession are consistently described as what draws it closer.',
        encFrom: 'From the Marble Hornets material',
        encIntro: 'The most influential accounts are not written stories but recovered-footage videos, whose gaps and glitches do more work than any description. One recurring detail is treated as canonical across otherwise unrelated retellings.',
        encBody: 'In the most-repeated version, the figure never appears when the camera is steady — only in the frames the operator later swears they did not shoot. The tapes are said to degrade a little more each time they are copied, as if watching them costs something.',
        galleryData: [
          { label: 'origin image', cap: 'One of the two 2009 photo-edits that started it all — a thin figure behind a group of children.' },
          { label: 'found footage', cap: 'Still from an early found-footage series; the figure at the treeline, slightly out of focus.' },
          { label: 'fan sigil', cap: 'The “Operator” symbol — a circle struck through — adopted by the community as shorthand.' },
          { label: 'forest photo', cap: 'A widely shared woodland photograph in which viewers insist a figure is present.' },
          { label: 'game still', cap: 'Screenshot from the 2012 survival game that carried the figure mainstream.' },
        ],
        popCap: 'Search and mention volume, indexed to 100. The 2010 found-footage wave produced the sharpest early spike; interest cooled after 2014 before a film-driven recovery.',
        theories: [
          { t: 'Tulpa / thoughtform', x: 'The idea that sustained collective belief can give a fiction a kind of functional reality — a favorite in-community reading of the figure.' },
          { t: 'Surveillance-age dread', x: 'A faceless watcher at the edge of the frame reads neatly as anxiety about being recorded, tracked, and never quite alone.' },
          { t: 'Memetic organism', x: 'Like the Rake, it survives only by being retold; each video, game, and drawing is another cell in the same body.' },
        ],
        myths: [
          { t: 'Not ancient folklore', x: 'Despite the fake woodcuts, the character was created in 2009 and has a named author.' },
          { t: 'Not public-domain from birth', x: 'Original ownership sat with its creator; wide fan use came later and unevenly.' },
          { t: 'Not the Rake', x: 'Frequently merged with the Rake, but the two have separate origins, silhouettes, and behaviors.' },
        ],
        references: [
          'Something Awful “Create Paranormal Images” thread, 2009 (community mirror).',
          'Marble Hornets episode index, 2010–2014.',
          '“The First Viral Monster,” essay on born-digital folklore, 2017.',
          'Survival-game postmortem and press coverage, 2012–2013.',
          '“Myth in the Network Age,” journal survey, 2020.',
          'Community sighting and media aggregation, 2009–present.',
        ],
        related: [
          { id: 'the-rake', name: 'The Rake', rel: 'Frequently conflated', threat: 82 },
          { id: 'the-mandela-catalogue', name: 'The Mandela Catalogue', rel: 'Faceless-alternate lineage', threat: 85 },
          { id: 'ben-drowned', name: 'BEN Drowned', rel: 'Found-footage contemporary', threat: 67 },
          { id: 'the-expressionless', name: 'The Expressionless', rel: 'Blank-face motif', threat: 71 },
        ],
        noteText: 'Editors are reviewing whether the 2014 real-world incident belongs in the History section or a separate “Impact” section handled with more care. Weigh in before it is merged.',
        comments: [
          { author: 'operator_db', role: 'Editor', time: '1 day ago', text: 'Reminder that the “German fairy-tale” images are fan-made in 2010, not sources. I’ve footnoted them in Origin.', votes: 91 },
          { author: 'staticwave', role: 'Contributor', time: '4 days ago', text: 'Marble Hornets did more to define the modern look than the original posts did. Should its influence get its own subsection?', votes: 57 },
          { author: 'thin_air', role: 'Reader', time: '2 weeks ago', text: 'First creepypasta I ever read. Wild to see it treated with actual citations instead of chain-mail energy.', votes: 33 },
        ],
        facts: { fThreatV: '88 · Severe', fDangerV: '80', fPopV: '96', species: 'Humanoid', status: 'Active', creator: 'Eric Knudsen', year: '2009', height: '~8 ft', canon: 'Community', habitat: 'Forests · suburbs · the treeline' },
        scoreNum: '4.8', ratingsCount: '9,540 ratings',
      },
      ru: {
        name: 'Slender Man', altName: 'Der Großmann', alsoPre: '«Тонкий человек» · также в архиве как ', bcCat: 'Классические крипипасты', kicker1: 'Современный миф · Сущность', kicker2: 'Канон сообщества',
        heroFirstV: '2009', heroOriginV: 'Веб-форум', heroThreatV: 'Высокая', heroPopV: '96', readTime: '21 мин чтения', ratingMeta: '/ 5 · 9 540 оценок',
        lead: 'Высокая безликая фигура в тёмном костюме, что маячит у кромки леса — и, кажется, истончает мысли всякого, кто смотрит слишком долго или слишком много ночей подряд.',
        ovP1: 'Слендермен — первый интернет-монстр с известной датой рождения. В отличие от фольклора, которому он подражает, он не выплыл из устной традиции — его выложили, датировали и подписали, а затем приняли так безоговорочно, что многие теперь считают его старше, чем он есть.',
        ovP2: 'Живучим его делает пустота. Лицо без черт — это экран: каждый читатель проецирует на него свой страх, и каждый пересказ волен переоформить фигуру, не сломав её. Пустота — это и есть замысел.',
        ovQuote: '«Мы не хотели идти, но он ждал за оградой, и почему-то на снимках он уже был вместе с нами.»',
        ovQuoteFoot: 'Сводная фраза — ранние форумные пересказы',
        orP1: 'Слендермена создал в июне 2009 года Эрик Кнудсен под ником «Victor Surge» для треда на Something Awful, где предлагалось вставлять паранормальные фигуры в обычные фотографии. Два обработанных чёрно-белых снимка — тонкая фигура позади детей — сопровождались выдуманными подписями о пропавших детях.',
        orP2: 'За несколько недель другие пользователи уже писали «свидетельства», подделывали документы и перекрёстно ссылались на выдумки друг друга, пока единый автор не исчез. Фотоконкурс превратился в коллективную мифологию, а его правило — считать подделку найденной — задало образец на десятилетие крипипаст.',
        orNote: 'У Слендермена есть задокументированный автор и дата создания. Любые «древние гравюры» или «немецкие сказки» — позднее фанатское украшение, а не источник, и архив помечает такие утверждения соответствующе.',
        history: [
          { t: '2009 · Создан', b: 'Опубликован в треде фоторедактуры на Something Awful; вокруг двух исходных снимков почти сразу начинают строить лор.' },
          { t: '2010 · Marble Hornets', b: 'Веб-сериал в жанре найденной плёнки превращает фигуру в снимаемое, преследующее присутствие и задаёт её визуальный язык.' },
          { t: '2012 · Игры', b: 'Минималистичная игра на выживание разносит персонажа далеко за пределы породивших его форумов.' },
          { t: '2014 · Общественное внимание', b: 'Реальное преступление, совершённое подростками со ссылкой на персонажа, вызывает шквал внимания СМИ и споры о сетевом фольклоре.' },
          { t: '2018–2024 · Кино и наука', b: 'Полнометражный фильм и растущий академический интерес к рождённому в сети мифу удерживают фигуру в широком обороте.' },
        ],
        behavior: [
          { t: 'Невозможный рост', x: 'Описывается неестественно высоким и худым, часто вытягивается или изгибается, когда за ним не наблюдают.' },
          { t: 'Пустое лицо', x: 'Безликая белая голова; свидетели сообщают о тревоге, которую потом не могут объяснить.' },
          { t: 'Тянущиеся конечности', x: 'В поздних рассказах добавляются длинные щупальцеобразные отростки, чтобы сгонять или уносить.' },
          { t: 'Фиксация и помехи', x: 'Долгое внимание, по слухам, приносит провалы в памяти, паранойю и искажения камеры.' },
        ],
        wk: 'Как и у большинства коллективных сущностей, надёжной слабости нет — фигура определяется неизбежностью, а не правилами, которые можно нарушить. Самая частая «защита» в рассказах — просто не искать его: внимание, съёмка и одержимость неизменно описываются как то, что притягивает его ближе.',
        encFrom: 'Из материалов Marble Hornets',
        encIntro: 'Самые влиятельные свидетельства — не письменные истории, а видео с «найденной плёнкой», где пропуски и помехи работают сильнее любого описания. Одна повторяющаяся деталь считается канонической в совершенно не связанных пересказах.',
        encBody: 'В самой распространённой версии фигура никогда не появляется при устойчивой камере — только в кадрах, которые оператор потом клянётся, что не снимал. Плёнки, как говорят, портятся чуть сильнее с каждой копией, будто просмотр чего-то стоит.',
        galleryData: [
          { label: 'исходный снимок', cap: 'Один из двух фотомонтажей 2009 года, с которых всё началось, — тонкая фигура позади группы детей.' },
          { label: 'найденная плёнка', cap: 'Стоп-кадр из раннего сериала о найденной плёнке; фигура у кромки леса, слегка не в фокусе.' },
          { label: 'фан-символ', cap: '«Символ Оператора» — перечёркнутый круг — принят сообществом как условное обозначение.' },
          { label: 'лесное фото', cap: 'Широко разошедшийся лесной снимок, на котором зрители уверяют, что присутствует фигура.' },
          { label: 'кадр из игры', cap: 'Скриншот из игры на выживание 2012 года, вынесшей фигуру в мейнстрим.' },
        ],
        popCap: 'Объём поисковых запросов и упоминаний, индекс 100. Волна найденной плёнки 2010 года дала самый резкий ранний всплеск; после 2014 года интерес остыл, а затем восстановился благодаря кино.',
        theories: [
          { t: 'Тульпа / мыслеформа', x: 'Идея, что устойчивая коллективная вера способна придать вымыслу своего рода функциональную реальность, — любимое внутрисообщественное прочтение фигуры.' },
          { t: 'Тревога эпохи слежки', x: 'Безликий наблюдатель на краю кадра легко читается как страх быть записанным, отслеженным и никогда не остаться в одиночестве.' },
          { t: 'Мемный организм', x: 'Как и Грабли, он выживает лишь пересказом; каждое видео, игра и рисунок — ещё одна клетка того же тела.' },
        ],
        myths: [
          { t: 'Не древний фольклор', x: 'Несмотря на поддельные гравюры, персонаж создан в 2009 году и имеет названного автора.' },
          { t: 'Не общественное достояние с рождения', x: 'Изначальные права принадлежали создателю; широкое фанатское использование пришло позже и неравномерно.' },
          { t: 'Не Грабли', x: 'Часто смешивают с Граблями, но у них разные происхождение, силуэт и поведение.' },
        ],
        references: [
          'Тред «Create Paranormal Images» на Something Awful, 2009 (зеркало сообщества).',
          'Указатель эпизодов Marble Hornets, 2010–2014.',
          '«Первый вирусный монстр», эссе о рождённом в сети фольклоре, 2017.',
          'Постмортем игры на выживание и пресса, 2012–2013.',
          '«Миф в сетевую эпоху», журнальный обзор, 2020.',
          'Агрегация свидетельств и медиа сообщества, 2009 — настоящее время.',
        ],
        related: [
          { id: 'the-rake', name: 'The Rake', rel: 'Часто путают', threat: 82 },
          { id: 'the-mandela-catalogue', name: 'The Mandela Catalogue', rel: 'Линия безликих двойников', threat: 85 },
          { id: 'ben-drowned', name: 'BEN Drowned', rel: 'Современник найденной плёнки', threat: 67 },
          { id: 'the-expressionless', name: 'The Expressionless', rel: 'Мотив пустого лица', threat: 71 },
        ],
        noteText: 'Редакторы решают, где место реальному инциденту 2014 года — в разделе «История» или в отдельном разделе «Влияние», поданном бережнее. Выскажитесь до слияния.',
        comments: [
          { author: 'operator_db', role: 'Редактор', time: '1 день назад', text: 'Напоминаю: «немецкие сказочные» изображения сделаны фанатами в 2010 году, это не источники. Я снабдил их сносками в «Происхождении».', votes: 91 },
          { author: 'staticwave', role: 'Участник', time: '4 дня назад', text: 'Marble Hornets сделал для современного облика больше, чем исходные посты. Стоит выделить его влияние в отдельный подраздел?', votes: 57 },
          { author: 'thin_air', role: 'Читатель', time: '2 недели назад', text: 'Первая крипипаста, что я прочитал. Странно видеть её с настоящими ссылками, а не с энергией письма счастья.', votes: 33 },
        ],
        facts: { fThreatV: '88 · Высокая', fDangerV: '80', fPopV: '96', species: 'Гуманоид', status: 'Активен', creator: 'Эрик Кнудсен', year: '2009', height: '~2,4 м', canon: 'Сообщество', habitat: 'Леса · пригороды · кромка леса' },
        scoreNum: '4.8', ratingsCount: '9 540 оценок',
      },
    },
  };

  window.KripiData = { UI: UI, ENTITIES: ENTITIES, order: ['the-rake', 'slender-man'] };
})();
